version: '3.1'

services:
  dbt:
    container_name: dbt_container
    image: ghcr.io/dbt-labs/dbt-postgres:1.2.latest
    tty: true
    volumes:
    - .:/usr/app
    working_dir: /usr/app
    networks:
      - postgres
    entrypoint: /bin/bash

  postgres:
    container_name: postgres_container
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
    postgres:
