
name: 'drug_pub_transform'
version: '1.0.0'
config-version: 2

profile: 'drug_pub_transform'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  drug_pub_transform:

    reservoir:
      +schema: rsv

    compute:
      +schema: cmp

    datamart:
      +schema: mrt
      +materialized: table

seeds:
  drug_pub_transform:
    +schema: seed

