drug_pub_transform:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres
      user: postgres
      password: changeme
      port: 5432
      dbname: postgres
      schema: dev
      threads: 4
